name: Copy GQL schema

on:
  push:
    tags:
      - v*

jobs:
  copy-file:
    runs-on: ubuntu-latest
    environment: copy-file
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /schema.gql
        src_branch: main
        dst_path: /app/gql/
        dst_owner: mansona
        dst_repo_name: test-copy-file-dest
        dst_branch: update-schema-${{github.ref}}
    - name: pull-request
      uses: m4heshd/pull-request@third-party-repos
      with:
        source_branch: update-schema-${{github.ref}}
        destination_branch: "main"
        destination_repository: "mansona/test-copy-file-dest"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "⬆️ Update GraphQL schema to match Facade ${{ github.ref }}"
        pr_label: "auto-pr"
